#define AMPERSAND                        1
#define AND                              2
#define PLUS                             3
#define MINUS                            4
#define TIMES                            5
#define DIVIDE                           6
#define POWER                            7
#define SQRT                             8
#define WRITE                            9
#define SEMICOLON                       10
#define IDENTIFIER                      11
#define ASSIGN                          12
#define TIME                            13
#define LPAR                            14
#define RPAR                            15
#define NUMTOKEN                        16
#define STRTOKEN                        17
#define NOT                             18
#define MAXIMUM                         19
#define MINIMUM                         20
#define FIRST                           21
#define LAST                            22
#define SUM                             23
#define COUNT                           24
#define LT                              25
#define GT                              26
#define OR                              27
#define IS                              28
#define WITHIN                          29
#define TO                              30
#define TRUE                            31
#define FALSE                           32
#define NUL_                            33
#define TIMESTAMP                       34
#define NOW                             35
#define IF                              36
#define THEN                            37
#define ENDIF                           38
#define ELSE                            39
#define ELSEIF                          40
#define LSPAR                           41
#define RSPAR                           42
#define COMMA                           43
#define OF                              44
