#define AMPERSAND                        1
#define AND                              2
#define PLUS                             3
#define MINUS                            4
#define TIMES                            5
#define DIVIDE                           6
#define POWER                            7
#define SQRT                             8
#define WRITE                            9
#define SEMICOLON                       10
#define IDENTIFIER                      11
#define ASSIGN                          12
#define TIME                            13
#define FOR                             14
#define IN                              15
#define DO                              16
#define ENDDO                           17
#define IF                              18
#define THEN                            19
#define ENDIF                           20
#define ELSE                            21
#define ELSEIF                          22
#define LPAR                            23
#define RPAR                            24
#define NUMTOKEN                        25
#define STRTOKEN                        26
#define NOT                             27
#define MAXIMUM                         28
#define MINIMUM                         29
#define FIRST                           30
#define LAST                            31
#define SUM                             32
#define COUNT                           33
#define IS                              34
#define NUMBER                          35
#define LIST                            36
#define EQUAL                           37
#define LT                              38
#define LTOE                            39
#define GT                              40
#define GTOE                            41
#define OR                              42
#define SEQTO                           43
#define WITHIN                          44
#define TO                              45
#define TRUE                            46
#define FALSE                           47
#define NUL_                            48
#define TIMESTAMP                       49
#define NOW                             50
#define CURRENTTIME                     51
#define LSPAR                           52
#define RSPAR                           53
#define COMMA                           54
#define OF                              55
