#define AMPERSAND                        1
#define OR                               2
#define AND                              3
#define NOT                              4
#define PLUS                             5
#define MINUS                            6
#define TIMES                            7
#define DIVIDE                           8
#define POWER                            9
#define SQRT                            10
#define UMINUS                          11
#define WRITE                           12
#define SEMICOLON                       13
#define IDENTIFIER                      14
#define ASSIGN                          15
#define TIME                            16
#define FOR                             17
#define IN                              18
#define DO                              19
#define ENDDO                           20
#define IF                              21
#define THEN                            22
#define ENDIF                           23
#define ELSE                            24
#define ELSEIF                          25
#define LPAR                            26
#define RPAR                            27
#define NUMTOKEN                        28
#define STRTOKEN                        29
#define MAXIMUM                         30
#define MINIMUM                         31
#define FIRST                           32
#define LAST                            33
#define SUM                             34
#define COUNT                           35
#define IS                              36
#define NUMBER                          37
#define LIST                            38
#define EQUAL                           39
#define LT                              40
#define LTOE                            41
#define GT                              42
#define GTOE                            43
#define SEQTO                           44
#define WITHIN                          45
#define TO                              46
#define TRUE                            47
#define FALSE                           48
#define NUL_                            49
#define TIMESTAMP                       50
#define NOW                             51
#define CURRENTTIME                     52
#define LSPAR                           53
#define RSPAR                           54
#define COMMA                           55
#define OF                              56
